import { ReactNode } from "react";
import { Montserrat } from "next/font/google";

import "./globals.css";

// eslint-disable-next-line new-cap
const montserrat = Montserrat({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Harper Media",
  // description: "Generated by create next app",
};

type RootLayoutProps = {
  children: ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps): JSX.Element {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
